version: '3'
services:
  database:
    image: postgres:15-alpine
    container_name: postgres15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=practice
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres:/var/lib/postgresql/data